import { COMBAT_CONFIG } from "./combat.mjs";
import { GEAR_STATES } from "./gear.mjs";
import { MOD_TYPES, WEAPON_MOD_FIELDS, WEAPON_MOD_MODES } from "./mods.mjs";
import { LEADER_PERMISSIONS, ROLE_CATEGORIES } from "./roles.mjs";

const STATS = {
  body: { label: 'Body', shortLabel: 'BODY', description: "Body represents your physical strength and durability. You'll need a high Body stat to survive taking a lot of damage, to put some force behind physical blows, and anything else where raw muscle comes in handy." },
  rflx: { label: 'Reflexes', shortLabel: 'RFLX', description: 'Reflexes represent your ability to move quickly, easily, and in coordinated. Using weapons that don\'t rely on force requires good reflexes, among many more applications.' },
  int:  { label: 'Intelligence', shortLabel: 'INT', description: 'Intelligence is a measure of your observational skills, deductive reasoning, and ability to think on your feet. With a high Intelligence stat, a character can handle most mental tasks thrown at them.' },
  tech: { label: 'Technological Ability', shortLabel: 'TECH', description: 'Technological Ability is the hands-on understanding of technology and its applications. A high score in this ability is a must for anyone who wants to build, repair, and use hardware.' },
  cool: { label: 'Cool', shortLabel: 'COOL', description: 'Cool is your social presence and ability to project confidence. A character with a high value in this stat will be popular wherever they go and might be able to take someone down through sheer attitude.' },
  move: { label: 'Move', shortLabel: 'MOVE', description: "In a round of combat you're able to move twice your MOVE meters along with another Action." },
};

const SKILLS = {
  acting: {
    label: 'Acting',
    stat: 'cool',
    components: [],
    description: "The ability to pretend. This skill is used to lie and swindle even more than it is on a stage, but the principle is the same: portray feelings and convictions you don't have. Acting is frequently an opposed check against a defender's INT + Human Perception.",
  },
  animals: {
    label: 'Animals',
    stat: 'cool',
    components: [],
    description: 'Critters appreciate you too. This skill is about training and caring for animals. Making friends with domesticated pets or riding a trained horse comes with a low DV if a roll is needed at all. Getting a starving coyote to trust you is more difficult.',
  },
  archery: {
    label: 'Archery',
    stat: 'rflx',
    components: [],
    description: 'The skill of using a bow and arrow or a crossbow. Good ranged weapons if you want to remain quiet. Using obscure trick-shots or gadget arrows are optional components that need to be discussed with the GM.',
  },
  athletics: {
    label: 'Athletics',
    stat: 'body',
    components: [],
    description: 'Jumping, running, throwing... The primary stat is about having the muscles, this skill is about putting them to good use. Most classic sports use this skill.',
  },
  autofire: {
    label: 'Autofire',
    stat: 'rflx',
    components: [],
    description: 'This skill is required to use the Autofire function of a weapon. The attack check uses the lower of the skill appropriate for the weapon (e.g. Handgun for an SMG or Shoulder Arms for an Assault Rifle) and this skill.',
  },
  business: {
    label: 'Business',
    stat: 'int',
    components: ['bureaucracy', 'businessStrategy', 'forgery'],
    description: 'How to successfully run a business, including ways to follow, circumvent, or break, laws and regulations. The skill allows you to bury irregularities or trade secrets. Uncovering such information is an opposed check against the original attempt at hiding.',
  },
  composition: {
    label: 'Composition',
    stat: 'cool',
    components: ['dancing', 'braindance', 'music', 'sculpting', 'visualArts', 'writing'],
    description: 'This is the skill of capturing thoughts and feelings into a medium of expression. The DV reflects the intended quality of the work. At +5 to the DV, you may hide a secondary message that is only clear to those with very specific cultural references.',
  },
  conceal: {
    label: 'Conceal',
    stat: 'int',
    components: [],
    description: "Looking for a place in your car where customs won't find your contraband? Going to palm that shard? Conceal is about your ability to prevent something from being found through a combination of clever hiding places and misdirection.",
  },
  contortionist: {
    label: 'Contortionist',
    stat: 'rflx',
    components: [],
    description: "With practice, you've learned how to twist your body in order to free yourself from restraints, move through narrow openings, and possibly more exotic things. Used with the INT stat, Contortionist can be used to tie someone up (setting the DV to break free).",
  },
  criminology: {
    label: 'Criminology',
    stat: 'int',
    components: [],
    description: "Dusting for prints, analyzing ballistics, and understanding police reports — all the technical aspects of crime fighting. Criminology can't answer 'why,' and maybe not 'who,' but it can usually shed some light as to 'how.'",
  },
  deduction: {
    label: 'Deduction',
    stat: 'int',
    components: [],
    description: "When your attempt to figure something out depends on understanding how pieces fit together rather than getting that information, that's Deduction. Other skills might let you find hidden documents, but this is the skill to tell you what's relevant in them. It's used to investigate clues, solve puzzles, etc.",
  },
  demolition: {
    label: 'Demolition',
    stat: 'tech',
    components: [],
    description: 'You know how to set up a controlled explosion. This includes calculating the right yield and location for charges, maintaining safety for those you want to keep safe, and effectively use grenades (when used with RFLX instead of TECH).',
  },
  drive: {
    label: 'Drive',
    stat: 'rflx',
    components: ['airVehicles', 'landVehicles', 'seaVehicles'],
    description: 'Characters are assumed to be able to drive a ground car well enough for a simple work commute. This skill allows you to use a vehicle in stressful situations and to safely operate any non-AI-guided air or sea vehicle.',
  },
  education: {
    label: 'Education',
    stat: 'int',
    components: [],
    description: 'This is your general level of education in everything from history to physics. It is rarely used to act directly, but can be invaluable for preparation. Or to impress the right people.',
  },
  electronics: {
    label: 'Electronics',
    stat: 'tech',
    components: ['basicTech', 'cybernetics', 'media', 'security', 'weaponstech'],
    description: 'This is the skill to build, repair, and manage delicate electronics. The corresponding skill for something with more moving parts is Mechanics.',
  },
  endurance: {
    label: 'Endurance',
    stat: 'body',
    components: [],
    description: 'This reflects your ability to withstand influences on your body. It helps keep the dangers of toxins and drugs at bay and to push through exhaustion. It even combines with TECH to keep your implants from being affected by outside disruption.',
  },
  evasion: {
    label: 'Evasion',
    stat: 'rflx',
    components: [],
    description: "When someone tries to hit you, best to get out of the way. This is vital in melee combat, but unless your RFLX is 8 or higher, you can't dodge bullets.",
  },
  gambling: {
    label: 'Gambling',
    stat: 'int',
    components: [],
    description: "Calculate odds and analyze strategies in games of chance. You can determine if someone's cheating, the odds are unusual, or gauge what kind of player the others are.",
  },
  government: {
    label: 'Government',
    stat: 'int',
    components: ['bureaucracy', 'businessStrategy', 'forgery', 'politics', 'publicInformation'],
    description: "This expertise enables you to navigate the public sector's complex network of corruption and bureaucracy. It's also a must for understanding how politics influence life and vice versa.",
  },
  handgun: {
    label: 'Handgun',
    stat: 'rflx',
    components: [],
    description: 'Using hand-held projectile weapons such as pistols. An unfamiliar type of handgun incurs a -1 or -2 penalty.',
  },
  hvyWeapons: {
    label: 'Heavy Weapons',
    stat: 'rflx',
    components: [],
    description: 'The skill to accurately use extremely large projectile weapons such as grenade and rocket launchers. An unfamiliar type of weapon incurs a -1 or -2 penalty.',
  },
  humanPerc: {
    label: 'Human Perception',
    stat: 'cool',
    components: [],
    description: 'Use this skill to understand what another is currently feeling, what likely caused it, and thus what their motivations might be.',
  },
  influence: {
    label: 'Influence',
    stat: 'cool',
    components: [],
    description: 'You know how to make someone you\'re talking to give you what you want, be it as items, information, or access. The skills cover everything from coaxing information, to seduction, to interrogating a suspect.',
  },
  martialArts: {
    label: 'Martial Arts',
    stat: 'body',
    components: ['aikido', 'brawling', 'karate', 'judo', 'taekwondo'],
    description: 'The skill to use your own body as a weapon without relying on implements. Each component comes with its own advantages.',
  },
  mechanics: {
    label: 'Mechanics',
    stat: 'tech',
    components: ['airVehicles', 'basicTech', 'cybernetics', 'landVehicles', 'robotics', 'seaVehicles', 'security', 'weaponstech'],
    description: 'This is the skill to build, repair, and manage mechanical systems and gadgets. The corresponding skill for circuitry is Electronics.',
  },
  medicine: {
    label: 'Medicine',
    stat: 'tech',
    components: [],
    description: 'This is the skill to treat injuries and other conditions. The basic usage represents only what paramedics can do and focuses on solving emergencies.',
  },
  meleeWeapons: {
    label: 'Melee Weapons',
    stat: 'body',
    components: [],
    description: 'Whenever you make a melee attack that takes advantage of an object, you\'re using this skill. Light Melee Weapons use RFLX as their primary stat; Medium Melee Weapons give you the option. An unfamiliar type of weapon incurs a -1 or -2 penalty. Improvised weapons are always at -2.',
  },
  netrunning: {
    label: 'Netrunner',
    stat: 'int',
    components: ['codebreak', 'cracker', 'dev', 'ghost', 'software', 'spider', 'quickhacking'],
    description: "Non-Netrunners can only use this for trouble-shooting or using the software on a computer with a regular interface, or to use commands that are part of their neuroport's UI.",
  },
  performance: {
    label: 'Performance',
    stat: 'cool',
    components: ['dancing', 'braindance', 'forgery', 'music', 'visualArts', 'publicSpeaking'],
    description: "While Acting is about convincingly portray a feeling or sincerity of a statement, Performance is about rallying a crowd and instill emotions in them. It's giving an inspirational speech, paint graffiti that brings hate to corpos, or play a concert to an audience leaving their worries behind for once.",
  },
  perception: {
    label: 'Perception',
    stat: 'int',
    components: [],
    description: 'This is the skill to pick up on details in your surroundings. It applies to attempts to eavesdrop as much as it does to spotting someone following you or noticing a tiny detail.',
  },
  pickLock: {
    label: 'Pick Lock',
    stat: 'tech',
    components: [],
    description: 'Provided you have access to good enough tools, this skill allows you to pick mechanical locks.',
  },
  shoulderArms: {
    label: 'Shoulder Arms',
    stat: 'rflx',
    components: [],
    description: 'This skill allows you to accurately fire larger projectile weapons, such as rifles and shotguns. An unfamiliar type of weapon incurs a -1 or -2 penalty.',
  },
  sleightOfHand: {
    label: 'Sleight-of-Hand',
    stat: 'rflx',
    components: [],
    description: 'This is the skill of taking or placing an object without being noticed (as opposed to Conceal, which is about finding ways to hide the object). It can be used to do card tricks or pocket wares in a store, for example.',
  },
  stealth: {
    label: 'Stealth',
    stat: 'rflx',
    components: [],
    description: 'The ability to remain unnoticed by those you want to hide from. A useful skill for many Edgerunners and essential to any breaking and entering.',
  },
  streetwise: {
    label: 'Streetwise',
    stat: 'cool',
    components: [],
    description: 'You know what drugs are popular, which gang controls what area of the city, which Fixer to talk to, and other aspects of being part of Street life.',
  },
  style: {
    label: 'Style',
    stat: 'cool',
    components: [],
    description: "This skill allows you to present yourself as attractive as possible (or something else, if being attractive isn't your goal). You can even use it to save your fashion-challenged friends from the worst embarrassment. Of course, Style allows for styling more than clothes.",
  },
  survival: {
    label: 'Survival',
    stat: 'int',
    components: [],
    description: 'This skill includes things like setting up a camp, foraging for safe enough food, following tracks, and other things for dealing with the great outdoors. Your lifepath is the guide to what environments you are used to. Applying what you know to an unfamiliar biome incurs at least a -1 or -2 penalty.',
  },
  tactics: {
    label: 'Tactics',
    stat: 'int',
    components: [],
    description: 'This skill allows you to plan larger scale combat effectively. Use it to predict reactions in enemy forces or find military weak-spots. A successful Tactics roll can find strategic weak points in defenses or to give a bonus to your allies under the right circumstances.',
  },
  trading: {
    label: 'Trading',
    stat: 'int',
    components: [],
    description: 'This skill helps you appraise a commodity, evaluate markets, and track down lucrative deals. It applies both on the small scale of street vendors and to large business contracts that cover billions in trade deals.',
  },
};

// Player-facing skill groupings for the Skills-tab overview. Object key order
// sets the order the groups appear in; each `skills` array just defines group
// membership — within a group the skills are displayed alphabetically by label
// (sorted in actor-sheet.mjs). Every skill slug should live in exactly one
// group — any skill missing from here is rendered under an "Other" fallback
// group rather than silently dropped.
const SKILL_CATEGORIES = {
  ranged:    { label: 'Ranged Combat',       skills: ['archery', 'autofire', 'handgun', 'hvyWeapons', 'shoulderArms'] },
  melee:     { label: 'Close Combat',         skills: ['martialArts', 'meleeWeapons', 'evasion'] },
  physical:  { label: 'Athletics & Agility',  skills: ['athletics', 'endurance', 'contortionist', 'drive'] },
  covert:    { label: 'Stealth & Larceny',    skills: ['stealth', 'conceal', 'pickLock', 'sleightOfHand'] },
  tech:      { label: 'Tech & Engineering',   skills: ['electronics', 'mechanics', 'demolition', 'netrunning', 'medicine'] },
  knowledge: { label: 'Investigation & Lore', skills: ['perception', 'deduction', 'criminology', 'education', 'tactics', 'survival', 'animals'] },
  social:    { label: 'Social & Influence',   skills: ['acting', 'influence', 'humanPerc', 'streetwise', 'style', 'performance', 'composition'] },
  trade:     { label: 'Trade & Society',      skills: ['business', 'trading', 'government', 'gambling'] },
};

const COMPONENT_LABELS = {
  aikido: 'Aikido',
  airVehicles: 'Air Vehicles',
  basicTech: 'Basic Tech',
  brawling: 'Brawling',
  bureaucracy: 'Bureaucracy',
  businessStrategy: 'Business Strategy',
  codebreak: 'Codebreak',
  cracker: 'Cracker',
  cybernetics: 'Cybernetics',
  dancing: 'Dancing',
  dev: 'Dev',
  braindance: 'Braindance',
  forgery: 'Forgery',
  ghost: 'Ghost',
  judo: 'Judo',
  karate: 'Karate',
  landVehicles: 'Land Vehicles',
  media: 'Media',
  music: 'Music',
  politics: 'Politics',
  publicInformation: 'Public Information',
  publicSpeaking: 'Public Speaking',
  quickhacking: 'Quickhacking',
  robotics: 'Robotics',
  sculpting: 'Sculpting',
  seaVehicles: 'Sea Vehicles',
  security: 'Security',
  software: 'Software',
  spider: 'Spider',
  taekwondo: 'Taekwondo',
  visualArts: 'Visual Arts',
  weaponstech: 'Weaponstech',
  writing: 'Writing',
};

const COMPONENT_DESCRIPTIONS = {
  aikido:           'This style represents forms with sweeping movements to lock and disarm opponents by turning their power against them.',
  airVehicles:      'From AV-4 "flying cars" to airplanes to giant transport aerozaps.',
  basicTech:        "All the general technology around that isn't a specific other Component. The everyday things that aren't important until they're everything.",
  braindance:       'The technology to record experiences to be relived by someone else later. It takes a lot to make those experiences feel genuine and interesting instead of a jumble of incoherent impressions.',
  brawling:         'Fighting that relies on heavy blows and good use of improvised weapons.',
  bureaucracy:      'Forms, permissions, and paper trail can be key to any investigation, ways to block an enemy, or an obstacle that needs to be overcome.',
  businessStrategy: "A corp that doesn't understand where to do business, and with whom isn't likely to last. A savvy investigator will notice the subcontractor that stands out, the suspicious absence from a trade show, or advertising that wouldn't actually move product.",
  codebreak:        'Requires NET Actions to be useful. Break through firewalls and encrypt/decrypt data.',
  cracker:          'Requires NET Actions to be useful. Deal with dangerous Black ICE programs trying to attack you within a subnet, or even with enemy Netrunners.',
  cybernetics:      'The technology of cyberware itself and the internal structures needed to both mimic and enhance human function.',
  dancing:          'Expression through artistic movements of the body. Usually along with music.',
  dev:              'The development and analysis of programs. Only someone with NET Actions can use it to develop or analyze programs that require such.',
  forgery:          'With Government or Business, the Component can replicate believable paperwork along with a fake signature. With Performance, it can replicate someone\'s handwriting.',
  ghost:            'Requires NET Actions to be useful. Hide within a network, sneaking into nodes undetected and wiping your traces afterwards.',
  judo:             'Soft techniques that focus on grabs, throws, and escapes.',
  karate:           'This form represents a focus on breaking bones and armor in order to crush their enemies.',
  landVehicles:     'Cars, motorcycles, trucks. Probably most vehicles you\'ll encounter.',
  media:            'There are many technologies for recording something, storing those recordings, and playing them back. This Component covers all of it.',
  music:            'Humanity has used music to express themselves for thousands of years. There\'s primal power there, ready to let a message move through an audience at the sound of the beat.',
  politics:         'Even with all the power of the corps, political leaders matter. If only for choosing which corp to sell out to. This Component comes with knowledge of politicians, the political system, and how to run for office.',
  publicInformation: 'A lot is actually available to anyone if you know where to ask and what to ask for. This is the skill for that. Get the right blueprints, signed applications, proof of employment, etc.',
  publicSpeaking:   'Wow the crowds with a rousing speech or a soulful poetry reading. Useful for rebels, politicians, and conspiracy theorists alike.',
  quickhacking:     "Requires NET Actions to be useful. Practically everyone has a Neuroport. This Component allows a Netrunner to hack it and upload a program that will cause the target's cyberware to malfunction in some way.",
  robotics:         "Autonomous mechanical agents are very useful for security work, surveillance drones, or any other task where you don't want to put humans at risk but it requires skill.",
  sculpting:        'The creation of objects as expression. The advantage is that the message you leave might be around for a long time.',
  seaVehicles:      "The oceans are dangerous to traverse, but they're extremely dangerous if you're not good at handling the boat or ship you're on.",
  security:         "Electronic locks, traps, security fields... There's so much technology that exists just to keep the wrong people out.",
  software:         "The only use of the Netrunning skill that doesn't require NET Actions. This skill is to use existing software effectively.",
  spider:           'Requires NET Actions to be useful. To use a network, you must know the network. This Component has to do with exploring nodes and interpreting the data there.',
  taekwondo:        'High-precision strikes that focus on causing severe injuries.',
  visualArts:       "Painting, graffiti, graphic design... It's all about conveying a message of some kind in a way that will make an impact.",
  weaponstech:      'To develop weapons requires some highly specific skills, but in this world, those skills are very much sought after.',
  writing:          'It is still one of the most trusted forms of communication. Not everyone reads longer works, but everyone has some Media whose writing they follow and takes to heart.',
};

function buildComponents(skills) {
  const components = {};

  for (const [skillSlug, skill] of Object.entries(skills)) {
    for (const componentSlug of skill.components) {
      if (!components[componentSlug]) {
        components[componentSlug] = {
          label: COMPONENT_LABELS[componentSlug] ?? componentSlug,
          description: COMPONENT_DESCRIPTIONS[componentSlug] ?? '',
          skills: [],
        };
      }

      components[componentSlug].skills.push(skillSlug);
    }
  }

  return components;
}

const COST_LADDER = [
  '€$10 (Cheap)',
  '€$20 (Everyday)',
  '€$50 (Costly)',
  '€$100 (Premium)',
  '€$500 (Expensive)',
  '€$1,000 (Very Expensive)',
  '€$5,000 (Luxury)',
  '€$10,000 (Super Luxury)',
];

const MANUFACTURERS = [
  '2nd Amendment',
  '6th Street',
  'Aerondight',
  'Aldecaldos',
  'AllFoods',
  'All World Insurance',
  'AmuTek',
  'Animals',
  'Aoba',
  'Arasaka',
  'Archer',
  'AT-AK',
  'Attuned In',
  'Avante',
  'Below Deck',
  'Biotechnica',
  'Bolshevik',
  'Brain Wash',
  'Braingasm',
  'Brennan',
  'Brooklyn Barista',
  'Buck-A-Slice',
  'Budget Arms',
  'Bumelant',
  'BuryGer',
  'Cali',
  'Capitan Caliente',
  'Centzon Totochtin',
  'Channel 54',
  'Chevillon',
  'Chromanticore',
  'Combat Cab',
  'Constitutional Arms',
  'Corp-Bud',
  'Dakai',
  'Darra-Polytechnic',
  'Data Inc',
  'Ded Zed',
  'Delamain',
  'Dynalar',
  'EBM',
  'El Guapo',
  'El Pinche Pollo',
  'European Space Agency',
  'Everest VentureWare',
  'Federated Arms',
  'Fuyutsuki',
  'Gibson Battlegear',
  'Impala Automatics',
  'Kang-Tao',
  'Kaukaz',
  'Kendachi',
  'Kiroshi',
  'KTech',
  'Lizzy-Wizzy',
  'Love Hub',
  'Maelstrom',
  'Mahir',
  'Makigai',
  'Malorian Arms',
  'MAX-TAC',
  'MetaCorp',
  'Microtech',
  'Midnight Arms',
  'Midnight Lady',
  'Milfguard',
  'Militech',
  'Mizutani',
  'Moore',
  'Mr Stud',
  'NC Industries',
  'NCART',
  'NCPD',
  'Netwatch',
  'Nicola',
  'Night City',
  'NightCorp',
  'Nokota',
  'Orbital Air',
  'Petrochem',
  'Quadra',
  'Raven Microcybernetics',
  'RCS',
  'RealWater',
  'Rostović',
  'Samurai',
  'Sanroo',
  'SoftSys',
  'SovOil',
  'Spunky Monkey',
  'Sternmeyer Ballistics',
  'Techtronika',
  'Moxes',
  'Trauma Team',
  'Tsunami Arms',
  'Tyger Claws',
  'Valentinos',
  'Vargas',
  'Villefort',
  'Voodoo Boys',
  'Wet Dream',
  'WNS',
  'Yaiba',
  'Zetatech',
  'Ziggy Q',
];

const CYBERWARE_TYPES = [
  { value: 'neuralware',  label: 'CYBER_BLUE.Cyberware.Type.neuralware' },
  { value: 'cyberoptics', label: 'CYBER_BLUE.Cyberware.Type.cyberoptics' },
  { value: 'cyberaudio',  label: 'CYBER_BLUE.Cyberware.Type.cyberaudio' },
  { value: 'cyberarms',   label: 'CYBER_BLUE.Cyberware.Type.cyberarms' },
  { value: 'cyberlegs',   label: 'CYBER_BLUE.Cyberware.Type.cyberlegs' },
  { value: 'internal',    label: 'CYBER_BLUE.Cyberware.Type.internal' },
  { value: 'external',    label: 'CYBER_BLUE.Cyberware.Type.external' },
  { value: 'fashionware', label: 'CYBER_BLUE.Cyberware.Type.fashionware' },
  { value: 'borgware',    label: 'CYBER_BLUE.Cyberware.Type.borgware' },
];

const CYBERWARE_INTEGRATIONS = [
  { value: 'platform',   label: 'CYBER_BLUE.Cyberware.IntegrationType.platform' },
  { value: 'extension',  label: 'CYBER_BLUE.Cyberware.IntegrationType.extension' },
  { value: 'standalone', label: 'CYBER_BLUE.Cyberware.IntegrationType.standalone' },
];

const CYBERWARE_FACILITIES = [
  { value: 'mall',     label: 'CYBER_BLUE.Cyberware.FacilityType.mall' },
  { value: 'clinic',   label: 'CYBER_BLUE.Cyberware.FacilityType.clinic' },
  { value: 'hospital', label: 'CYBER_BLUE.Cyberware.FacilityType.hospital' },
];

export const CYBER_BLUE = {
  stats: STATS,
  skills: SKILLS,
  skillCategories: SKILL_CATEGORIES,
  components: buildComponents(SKILLS),
  costLadder: COST_LADDER,
  manufacturers: MANUFACTURERS,
  resources: {
    hp:     { label: 'HP',     description: "Hit Points track how much of a beating you can take. As you take damage, certain thresholds indicate serious wounds as well as risks of dying. You can't heal above your max HP." },
    psyche: { label: 'PSYCHE', description: 'When things make you feel like less of a real person you get less stable. Cyberware, especially, will also lower how much you can restore your mental health, even with treatment.' },
    luck:   { label: 'LUCK',   description: 'Luck helps players tell the story they want. You spend it after you roll by adding +1 per point spent. They are regained when you chill out and at the GM\'s discretion. NPCs never have a LUCK stat.' },
  },
  healthItemDescriptions: {
    seriousWound:  'Half your max HP. When your current HP fall below this, you are Seriously Wounded and suffer -2 on all checks.',
    deathSave:     "If you've reached 0 HP, you must roll this number (usually your BODY) or below on 1d10 each round or go unconscious. If you're already unconscious, you die.",
    stoppingPower: 'Stopping Power is the amount your armor protects you. Incoming damage is reduced by SP. If the remaining damage is 0 or higher, the SP is reduced by 1.',
  },
  tableHeaderDescriptions: {
    targetVitals: '-8 to hit the target\'s vulnerabilities — such as their head.',
    rateOfFire:   'Rate of Fire. The number of times you can attack with the weapons for a single Attack Action.',
    mag:          'How much ammo do you have left?',
    concealable:  'Can this weapon be concealed?',
    integration:  'Platforms are the foundation for other Extension cyberware which uses up their slots.',
    platform:     'What platform is the extension currently installed on?',
  },
  cyberware: {
    types: CYBERWARE_TYPES,
    integrations: CYBERWARE_INTEGRATIONS,
    facilities: CYBERWARE_FACILITIES,
  },
  roles: {
    categories: ROLE_CATEGORIES,
    leaderPermissions: LEADER_PERMISSIONS,
  },
  combat: COMBAT_CONFIG,
  gearStates: GEAR_STATES,
  modifications: {
    types: MOD_TYPES,
    weaponFields: WEAPON_MOD_FIELDS,
    weaponModes: WEAPON_MOD_MODES,
  },
  activeEffects: {
    cyberwareDisable: {
      name: 'cyberblue.disableCyberware.name',
      type: 'cyberblue.disableCyberware.type',
      random: 'cyberblue.disableCyberware.random',
      randomType: 'cyberblue.disableCyberware.randomType',
    },
  },
  itemTypes: {
    role:              { label: 'TYPES.Item.role' },
    ability:           { label: 'TYPES.Item.ability' },
    cyberware:         { label: 'TYPES.Item.cyberware' },
    gear:              { label: 'TYPES.Item.gear' },
    drug:              { label: 'TYPES.Item.drug' },
    programExecutable: { label: 'TYPES.Item.programExecutable' },
    mod:               { label: 'TYPES.Item.mod' },
  },
};
